# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=128)),
                ('attribution', models.CharField(max_length=64)),
                ('submitter_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
