# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_submittedquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedquote',
            name='date_submitted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
