# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_submittedquote_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='num_ratings',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
