# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170321_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
