# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170322_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedquote',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
