# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-31 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170327_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='censored_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
